const translations = {
    es: {
        meta_title: "JONATHAN GÓMEZ",
        lbl_idioma: "IDIOMA",
        lbl_edition: "SOCCER MEXICO-AMERICANO",
        lbl_hero_title: "JONATHAN GÓMEZ",
        btn_conoceme: "CONOCEME",
        btn_portafolio: "PORTAFOLIO DE IMAGENES",
        btn_poder_musica: "GRANDES MOMENTOS",
        btn_contacto: "REDES SOCIALES",
        lbl_clic_reproducir: "CLIC PARA REPRODUCIR",
        btn_grandes_momentos: "GRANDES MOMENTOS",
        modal_grandes_momentos_title: "GRANDES MOMENTOS",
        modal_grandes_momentos_desc: "Toca una imagen para ampliarla y deslizarla",
        btn_cerrar: "Cerrar",
        btn_comparte_historia: "COMPARTIR",
        lbl_producido_por: "PRODUCIDO POR \"TALENT CARD\"",
        btn_contactanos_card: "CONTÁCTANOS",
        lbl_conoceme: "CONOCEME",
        lbl_biografia: "Biografía",
        lbl_nombre_label: "Nombre:",
        val_nombre: "Jonathan Germán Gómez Mendoza",
        lbl_edad_label: "Posición:",
        val_edad: "Lateral Izquierdo / Defensor",
        lbl_nacimiento_label: "Origen:",
        val_nacimiento: "Fort Worth, Texas (Herencia Mexicana)",
        lbl_nacionalidad_label: "Nacionalidad:",
        val_nacionalidad: "Mexicoamericana",
        lbl_estatura_label: "Perfil / Trayectoria:",
        val_estatura: "Futbolista de Élite Internacional",
        lbl_formacion_titulo: "Formación Profesional",
        lbl_perfil_label: "Perfil:",
        val_perfil_text: "Atleta profesional de alto rendimiento con experiencia en el fútbol europeo (Real Sociedad B), la Major League Soccer (MLS) y convocatorias a selecciones nacionales.",
        lbl_desempeno_label: "Desempeño:",
        val_desempeno_text: "Reconocido por su desborde ofensivo, solidez defensiva, lectura táctica avanzada y una entrega absoluta en cada partido disputado.",
        lbl_especialidad_titulo: "Especialidad",
        lbl_disciplina_label: "Disciplina:",
        val_disciplina_text: "Lateral izquierdo con vocación de ataque, transiciones dinámicas y rigor táctico bajo la máxima exigencia competitiva.",
        lbl_tecnica_label: "Técnica:",
        val_tecnica_text: "Dominio técnico de perfil zurdo, precisión en centros, intensidad en la marca y mentalidad ganadora forjada en escenarios internacionales.",
        lbl_logros_titulo: "Logros y Trayectoria",
        val_logro_1: "📌 Consolidación en el balompié internacional con pasos destacados en el fútbol de alta competencia en Europa y Norteamérica, demostrando adaptabilidad y carácter.",
        val_logro_2: "⚽ Protagonista en duelos de alta presión y torneos internacionales, representando con orgullo sus raíces y dejando constancia de su talento en la cancha.",
        val_logro_3: "🌐 Un deportista excepcional y un ser humano íntegro, distinguido por su disciplina inquebrantable, liderazgo positivo dentro y fuera del campo, y su incansable afán de superación.",
        btn_regresar_menu: "REGRESAR AL MENÚ 🚀",
        contact_title: "REDES SOCIALES",
        contact_contracting: "Redes sociales",
        btn_facebook: "FACEBOOK",
        btn_instagram: "INSTAGRAM",
        qr_heading: "ESCANEA EL CÓDIGO QR",
        btn_share_qr: "COMPARTIR QR",
        cat2_t: "PORTAFOLIO DE IMAGENES",
        cat2_c: "La grandeza en la cancha es fruto de una disciplina inquebrantable y un esfuerzo constante. Con entrega total y un compromiso absoluto en cada partido, ha demostrado que el éxito combina talento y perseverancia, inspirando a otros a perseguir sus sueños con el corazón.",
        cat3_t: "GRANDES MOMENTOS",
        cat3_c: "Competir en los escenarios más exigentes del fútbol internacional significa llevar el orgullo de México y de sus raíces al máximo nivel. Cada partido es el resultado de una disciplina inquebrantable y el honor de representar con pasión, entrega y autenticidad en la cancha.",
        lbl_mis_fortalezas: "México en el corazón",
        btn_tributo_tri: "Gol de Jonathan",
        btn_junto_mar: "Entrevista con el Albacete",
        btn_con_gente: "La joya escondida de México",
        btn_ver_detalles: "VER DETALLES"
    },
    en: {
        meta_title: "JONATHAN GÓMEZ",
        lbl_idioma: "LANGUAGE",
        lbl_edition: "MEXICAN-AMERICAN SOCCER",
        lbl_hero_title: "JONATHAN GÓMEZ",
        btn_conoceme: "ABOUT ME",
        btn_portafolio: "IMAGE PORTFOLIO",
        btn_poder_musica: "GREAT MOMENTS",
        btn_contacto: "SOCIAL MEDIA",
        lbl_clic_reproducir: "CLICK TO PLAY",
        btn_grandes_momentos: "GREAT MOMENTS",
        modal_grandes_momentos_title: "GREAT MOMENTS",
        modal_grandes_momentos_desc: "Tap an image to zoom and swipe",
        btn_cerrar: "Close",
        btn_comparte_historia: "SHARE",
        lbl_producido_por: "PRODUCED BY \"TALENT CARD\"",
        btn_contactanos_card: "CONTACT US",
        lbl_conoceme: "ABOUT ME",
        lbl_biografia: "Biography",
        lbl_nombre_label: "Name:",
        val_nombre: "Jonathan Germán Gómez Mendoza",
        lbl_edad_label: "Position:",
        val_edad: "Left Back / Defender",
        lbl_nacimiento_label: "Origin:",
        val_nacimiento: "Fort Worth, Texas (Mexican Heritage)",
        lbl_nacionalidad_label: "Nationality:",
        val_nacionalidad: "Mexican-American",
        lbl_estatura_label: "Profile / Career:",
        val_estatura: "International Elite Soccer Player",
        lbl_formacion_titulo: "Professional Background",
        lbl_perfil_label: "Profile:",
        val_perfil_text: "High-performance professional athlete with experience in European football (Real Sociedad B), Major League Soccer (MLS), and national team call-ups.",
        lbl_desempeno_label: "Performance:",
        val_desempeno_text: "Recognized for his offensive overlap, defensive solidity, advanced tactical awareness, and absolute dedication in every match played.",
        lbl_especialidad_titulo: "Specialty",
        lbl_disciplina_label: "Discipline:",
        val_disciplina_text: "Left-back with an attacking vocation, dynamic transitions, and tactical rigor under maximum competitive pressure.",
        lbl_tecnica_label: "Technique:",
        val_tecnica_text: "Left-footed technical mastery, precision in crosses, intensity in marking, and a winning mindset forged on international stages.",
        lbl_logros_titulo: "Achievements & Career",
        val_logro_1: "📌 Consolidation in international football with prominent steps in high-competition football in Europe and North America, showing adaptability and character.",
        val_logro_2: "⚽ Protagonist in high-pressure duels and international tournaments, proudly representing his roots and demonstrating his talent on the pitch.",
        val_logro_3: "🌐 An exceptional athlete and an integral human being, distinguished by his unwavering discipline, positive leadership on and off the field, and tireless drive for self-improvement.",
        btn_regresar_menu: "BACK TO MENU 🚀",
        contact_title: "SOCIAL MEDIA",
        contact_contracting: "Social media",
        btn_facebook: "FACEBOOK",
        btn_instagram: "INSTAGRAM",
        qr_heading: "SCAN THE QR CODE",
        btn_share_qr: "SHARE QR",
        cat2_t: "IMAGE PORTFOLIO",
        cat2_c: "Greatness on the pitch is the result of unwavering discipline and constant effort. With total dedication and absolute commitment in every match, he has shown that success combines talent and perseverance, inspiring others to pursue their dreams with heart.",
        cat3_t: "GREAT MOMENTS",
        cat3_c: "Competing in the most demanding stages of international football means bringing the pride of Mexico and his roots to the highest level. Every match is the result of unwavering discipline and the honor of representing with passion, dedication, and authenticity on the pitch.",
        lbl_mis_fortalezas: "Mexico in the heart",
        btn_tributo_tri: "Jonathan's Goal",
        btn_junto_mar: "Interview with Albacete",
        btn_con_gente: "Mexico's Hidden Gem",
        btn_ver_detalles: "VIEW DETAILS"
    },
    pt: {
        meta_title: "JONATHAN GÓMEZ",
        lbl_idioma: "IDIOMA",
        lbl_edition: "FUTEBOL MÉXICO-AMERICANO",
        lbl_hero_title: "JONATHAN GÓMEZ",
        btn_conoceme: "CONHECE-ME",
        btn_portafolio: "PORTFÓLIO DE IMAGENS",
        btn_poder_musica: "GRANDES MOMENTOS",
        btn_contacto: "REDES SOCIAIS",
        lbl_clic_reproducir: "CLIQUE PARA REPRODUZIR",
        btn_grandes_momentos: "GRANDES MOMENTOS",
        modal_grandes_momentos_title: "GRANDES MOMENTOS",
        modal_grandes_momentos_desc: "Toque em uma imagem para ampliar e deslizar",
        btn_cerrar: "Fechar",
        btn_comparte_historia: "COMPARTILHAR",
        lbl_producido_por: "PRODUZIDO POR \"TALENT CARD\"",
        btn_contactanos_card: "CONTATE-NOS",
        lbl_conoceme: "CONHECE-ME",
        lbl_biografia: "Biografia",
        lbl_nombre_label: "Nome:",
        val_nombre: "Jonathan Germán Gómez Mendoza",
        lbl_edad_label: "Posição:",
        val_edad: "Lateral Esquerdo / Defensor",
        lbl_nacimiento_label: "Origem:",
        val_nacimiento: "Fort Worth, Texas (Herança Mexicana)",
        lbl_nacionalidad_label: "Nacionalidade:",
        val_nacionalidad: "Mexicano-americana",
        lbl_estatura_label: "Perfil / Trajetória:",
        val_estatura: "Jogador de Futebol de Elite Internacional",
        lbl_formacion_titulo: "Formação Profissional",
        lbl_perfil_label: "Perfil:",
        val_perfil_text: "Atleta profissional de alto rendimento com experiência no futebol europeu (Real Sociedad B), Major League Soccer (MLS) e convocações para seleções nacionais.",
        lbl_desempeno_label: "Desempenho:",
        val_desempeno_text: "Reconhecido por sua subida ofensiva, solidez defensiva, leitura tática avançada e entrega absoluta em cada partida disputada.",
        lbl_especialidad_titulo: "Especialidade",
        lbl_disciplina_label: "Disciplina:",
        val_disciplina_text: "Lateral esquerdo com vocação ofensiva, transições dinâmicas e rigor tático sob a máxima exigência competitiva.",
        lbl_tecnica_label: "Técnica:",
        val_tecnica_text: "Domínio técnico de pé esquerdo, precisão em cruzamentos, intensidade na marcação e mentalidade vencedora forjada em cenários internacionais.",
        lbl_logros_titulo: "Conquistas e Trajetória",
        val_logro_1: "📌 Consolidação no futebol internacional com passagens de destaque no futebol de alta competição na Europa e América do Norte, demonstrando adaptabilidade e caráter.",
        val_logro_2: "⚽ Protagonista em duelos de alta pressão e torneios internacionais, representando com orgulho suas raízes e deixando sua marca de talento em campo.",
        val_logro_3: "🌐 Um atleta excepcional e um ser humano íntegro, distinguido por sua disciplina inabalável, liderança positiva dentro e fora de campo e busca incansable pela superação.",
        btn_regresar_menu: "VOLTAR AO MENU 🚀",
        contact_title: "REDES SOCIAIS",
        contact_contracting: "Redes sociais",
        btn_facebook: "FACEBOOK",
        btn_instagram: "INSTAGRAM",
        qr_heading: "ESCANEIE O CÓDIGO QR",
        btn_share_qr: "COMPARTILHAR QR",
        cat2_t: "PORTFÓLIO DE IMAGENS",
        cat2_c: "A grandeza em campo é fruto de uma disciplina inabalável e de um esforço constante. Com dedicação total e compromisso absoluto em cada partida, ele demonstrou que o sucesso combina talento e perseverança, inspirando outros a perseguir seus sonhos com o coração.",
        cat3_t: "GRANDES MOMENTOS",
        cat3_c: "Competir nos cenários mais exigentes do futebol internacional significa levar o orgulho do México e de suas raízes ao nível máximo. Cada partida é o resultado de uma disciplina inabalável e da honra de representar com paixão, entrega e autenticidade em campo.",
        lbl_mis_fortalezas: "México no coração",
        btn_tributo_tri: "Gol de Jonathan",
        btn_junto_mar: "Entrevista com o Albacete",
        btn_con_gente: "A joia escondida do México",
        btn_ver_detalles: "VER DETALHES"
    },
    fr: {
        meta_title: "JONATHAN GÓMEZ",
        lbl_idioma: "LANGUE",
        lbl_edition: "FOOTBALL MEXICAIN-AMÉRICAIN",
        lbl_hero_title: "JONATHAN GÓMEZ",
        btn_conoceme: "À PROPOS",
        btn_portafolio: "PORTEFEUILLE D'IMAGES",
        btn_poder_musica: "GRANDS MOMENTS",
        btn_contacto: "RÉSEAUX SOCIAUX",
        lbl_clic_reproducir: "CLIQUEZ POUR LIRE",
        btn_grandes_momentos: "GRANDS MOMENTS",
        modal_grandes_momentos_title: "GRANDS MOMENTS",
        modal_grandes_momentos_desc: "Touchez une image pour zoomer et faire glisser",
        btn_cerrar: "Fermer",
        btn_comparte_historia: "PARTAGER",
        lbl_producido_por: "PRODUIT PAR \"TALENT CARD\"",
        btn_contactanos_card: "CONTACTEZ-NOUS",
        lbl_conoceme: "À PROPOS",
        lbl_biografia: "Biographie",
        lbl_nombre_label: "Nom:",
        val_nombre: "Jonathan Germán Gómez Mendoza",
        lbl_edad_label: "Poste:",
        val_edad: "Arrière Gauche / Défenseur",
        lbl_nacimiento_label: "Origine:",
        val_nacimiento: "Fort Worth, Texas (Héritage Mexicain)",
        lbl_nacionalidad_label: "Nationalité:",
        val_nacionalidad: "Mexicano-américaine",
        lbl_estatura_label: "Profil / Carrière:",
        val_estatura: "Footballeur d'Élite Internationale",
        lbl_formacion_titulo: "Parcours Professionnel",
        lbl_perfil_label: "Profil:",
        val_perfil_text: "Athlète professionnel de haut niveau avec une expérience dans le football européen (Real Sociedad B), en Major League Soccer (MLS) et des sélections en équipes nationales.",
        lbl_desempeno_label: "Performance:",
        val_desempeno_text: "Reconnu pour son apport offensif, sa solidité défensive, sa lecture tactique avancée et son engagement absolu lors de chaque match disputé.",
        lbl_especialidad_titulo: "Spécialité",
        lbl_disciplina_label: "Discipline:",
        val_disciplina_text: "Arrière gauche doté d'une vocation offensive, de transitions dynamiques et d'une rigueur tactique sous la plus haute exigence compétitive.",
        lbl_tecnica_label: "Technique:",
        val_tecnica_text: "Maîtrise technique du pied gauche, précision dans les centres, intensité au marquage et mentalité de vainqueur forgée sur la scène internationale.",
        lbl_logros_titulo: "Réalisations et Carrière",
        val_logro_1: "📌 Consolidation dans le football international avec des passages remarqués dans le football de haute compétition en Europe et en Amérique du Nord, démontrant adaptabilité et caractère.",
        val_logro_2: "⚽ Protagoniste dans les duels sous haute pression et les tournois internationaux, représentant fièrement ses racines et laissant une empreinte de son talent sur le terrain.",
        val_logro_3: "🌐 Un athlète exceptionnel et un être humain intègre, distingué par sa discipline inébranlable, son leadership positif sur et hors du terrain, et sa quête constante de dépassement de soi.",
        btn_regresar_menu: "RETOOUR AU MENU 🚀",
        contact_title: "RÉSEAUX SOCIAUX",
        contact_contracting: "Réseaux sociaux",
        btn_facebook: "FACEBOOK",
        btn_instagram: "INSTAGRAM",
        qr_heading: "SCANNEZ LE CODE QR",
        btn_share_qr: "PARTAGER QR",
        cat2_t: "PORTEFEUILLE D'IMAGES",
        cat2_c: "La grandeur sur le terrain est le fruit d'une discipline inébranlable et d'un effort constant. Avec un engagement total et un dévouement absolu dans chaque match, il a démontré que le succès combine talent et persévérance, inspirant les autres à poursuivre leurs rêves avec le cœur.",
        cat3_t: "GRANDS MOMENTS",
        cat3_c: "Concurrencer sur les scènes les plus exigeantes du football international signifie porter la fierté du Mexique et de ses racines au plus haut niveau. Chaque match est le résultat d'une discipline inébranlable et de l'honneur de représenter avec passion, dévouement et authenticité sur le terrain.",
        lbl_mis_fortalezas: "Le Mexique dans le cœur",
        btn_tributo_tri: "But de Jonathan",
        btn_junto_mar: "Entretien avec Albacete",
        btn_con_gente: "Le joyau caché du Mexique",
        btn_ver_detalles: "VOIR LES DÉTAILS"
    },
    ko: {
        meta_title: "JONATHAN GÓMEZ",
        lbl_idioma: "언어",
        lbl_edition: "멕시코계 미국인 축구",
        lbl_hero_title: "JONATHAN GÓMEZ",
        btn_conoceme: "나에 대해",
        btn_portafolio: "이미지 포트폴리오",
        btn_poder_musica: "위대한 순간들",
        btn_contacto: "소셜 미디어",
        lbl_clic_reproducir: "재생하려면 클릭",
        btn_grandes_momentos: "위대한 순간들",
        modal_grandes_momentos_title: "위대한 순간들",
        modal_grandes_momentos_desc: "이미지를 터치하여 확대하고 슬라이드하세요",
        btn_cerrar: "닫기",
        btn_comparte_historia: "공유하기",
        lbl_producido_por: "제작: \"TALENT CARD\"",
        btn_contactanos_card: "문의하기",
        lbl_conoceme: "나에 대해",
        lbl_biografia: "전기",
        lbl_nombre_label: "이름:",
        val_nombre: "Jonathan Germán Gómez Mendoza",
        lbl_edad_label: "포지션:",
        val_edad: "레프트 백 / 수비수",
        lbl_nacimiento_label: "출신:",
        val_nacimiento: "텍사스 주 포트워스 (멕시코 혈통)",
        lbl_nacionalidad_label: "국적:",
        val_nacionalidad: "멕시코계 미국인",
        lbl_estatura_label: "프로필 / 경력:",
        val_estatura: "국제 엘리트 축구 선수",
        lbl_formacion_titulo: "전문 경력 배경",
        lbl_perfil_label: "프로필:",
        val_perfil_text: "유럽 축구(레알 소시에다드 B), 미국 메이저 리그 사커(MLS) 및 국가대표팀 발탁 경험을 가진 고성능 프로 운동선수.",
        lbl_desempeno_label: "활약상:",
        val_desempeno_text: "공격 가담, 수비 견고함, 고급 전술 이해도, 그리고 매 경기 보여주는 절대적인 헌신으로 인정받고 있습니다.",
        lbl_especialidad_titulo: "전문 분야",
        lbl_disciplina_label: "포지션 규율:",
        val_disciplina_text: "공격 성향, 역동적인 전환, 최고 수준의 경쟁 속에서의 전술적 엄격함을 갖춘 레프트 백.",
        lbl_tecnica_label: "기술:",
        val_tecnica_text: "왼발 기술 숙련도, 크로스 정확도, 마킹 강도, 국제 무대에서 다져진 위닝 멘탈리티.",
        lbl_logros_titulo: "주요 성과 및 경력",
        val_logro_1: "📌 유럽과 북미의 고강도 경쟁 무대에서 주목할 만한 행보를 보이며 적응력과 캐릭터를 증명하고 국제 축구계에서 입지를 다짐.",
        val_logro_2: "⚽ 고압박 경기와 국제 토너먼트의 주역으로 활약하며 자신의 뿌리를 자랑스럽게 알리고 그라운드 위에서 재능을 증명.",
        val_logro_3: "🌐 흔들리지 않는 규율, 그라운드 안팎에서의 긍정적 리더십, 끊임없는 자기 발전의 의지로 구별되는 뛰어난 운동선수이자 온전한 인격체.",
        btn_regresar_menu: "메뉴로 돌아가기 🚀",
        contact_title: "소셜 미디어",
        contact_contracting: "소셜 미디어",
        btn_facebook: "FACEBOOK",
        btn_instagram: "INSTAGRAM",
        qr_heading: "QR 코드를 스캔하세요",
        btn_share_qr: "QR 공유",
        cat2_t: "이미지 포트폴리오",
        cat2_c: "그라운드 위에서의 위대함은 흔들리지 않는 규율과 꾸준한 노력의 결실입니다. 매 경기마다 보여준 전적인 헌신과 절대적인 몰입은 성공이 재능과 끈기의 결합임을 증명하며, 다른 이들이 마음으로 꿈을 좇도록 영감을 줍니다.",
        cat3_t: "위대한 순간들",
        cat3_c: "국제 축구의 가장 까다로운 무대에서 경쟁한다는 것은 멕시코의 자부심과 뿌리를 최고 수준으로 끌어올리는 것을 의미합니다. 모든 경기는 흔들리지 않는 규율과 열정, 헌신, 진정성으로 그라운드를 누비는 명예의 결과물입니다.",
        lbl_mis_fortalezas: "마음속의 멕시코",
        btn_tributo_tri: "조나단의 골",
        btn_junto_mar: "알바세테 인터뷰",
        btn_con_gente: "멕시코의 숨겨진 보석",
        btn_ver_detalles: "세부정보 보기"
    },
    de: {
        meta_title: "JONATHAN GÓMEZ",
        lbl_idioma: "SPRACHE",
        lbl_edition: "MEXIKANISCH-AMERIKANISCHER FUSSBALL",
        lbl_hero_title: "JONATHAN GÓMEZ",
        btn_conoceme: "ÜBER MICH",
        btn_portafolio: "BILDERPORTFOLIO",
        btn_poder_musica: "GROSSE MOMENTE",
        btn_contacto: "SOZIALE MEDIEN",
        lbl_clic_reproducir: "KLICKEN ZUM ABSPIELEN",
        btn_grandes_momentos: "GROSSE MOMENTE",
        modal_grandes_momentos_title: "GROSSE MOMENTE",
        modal_grandes_momentos_desc: "Tippen Sie auf ein Bild, um es zu vergrößern und zu wischen",
        btn_cerrar: "Schließen",
        btn_comparte_historia: "TEILEN",
        lbl_producido_por: "PRODUZIERT VON \"TALENT CARD\"",
        btn_contactanos_card: "KONTAKTIEREN SIE UNS",
        lbl_conoceme: "ÜBER MICH",
        lbl_biografia: "Biografie",
        lbl_nombre_label: "Name:",
        val_nombre: "Jonathan Germán Gómez Mendoza",
        lbl_edad_label: "Position:",
        val_edad: "Linker Verteidiger / Defensivspieler",
        lbl_nacimiento_label: "Herkunft:",
        val_nacimiento: "Fort Worth, Texas (Mexikanisches Erbe)",
        lbl_nacionalidad_label: "Nationalität:",
        val_nacionalidad: "Mexikanisch-amerikanisch",
        lbl_estatura_label: "Profil / Karriere:",
        val_estatura: "Internationaler Elite-Fussballer",
        lbl_formacion_titulo: "Beruflicher Hintergrund",
        lbl_perfil_label: "Profil:",
        val_perfil_text: "Leistungsstarker Profisportler mit Erfahrung im europäischen Fussball (Real Sociedad B), der Major League Soccer (MLS) und Nominierungen für Nationalmannschaften.",
        lbl_desempeno_label: "Leistung:",
        val_desempeno_text: "Bekannt für seinen Offensivdrang, defensive Solidität, fortgeschrittenes taktisches Verständnis und absoluten Einsatz in jedem bestrittenen Spiel.",
        lbl_especialidad_titulo: "Spezialität",
        lbl_disciplina_label: "Disziplin:",
        val_disciplina_text: "Linker Verteidiger mit Offensivdrang, dynamischen Übergängen und taktischer Strenge unter höchstem Wettbewerbsdruck.",
        lbl_tecnica_label: "Technik:",
        val_tecnica_text: "Technische Beherrschung mit dem linken Fuß, Präzision bei Flanken, Intensität im Zweikampf und eine auf internationaler Bühne geschmiedete Siegermentalität.",
        lbl_logros_titulo: "Erfolge und Karriere",
        val_logro_1: "📌 Konsolidierung im internationalen Fussball mit markanten Schritten im hochkompetitiven Fussball in Europa und Nordamerika, was Anpassungsfähigkeit und Charakter beweist.",
        val_logro_2: "⚽ Protagonist in Duellen unter hohem Druck und internationalen Turnieren, der stolz seine Wurzeln repräsentiert und sein Talent auf dem Platz unter Beweis stellt.",
        val_logro_3: "🌐 Ein außergewöhnlicher Sportler und integre Persönlichkeit, ausgezeichnet durch unerschütterliche Disziplin, positive Führung auf und neben dem Platz sowie unermüdlichen Ehrgeiz.",
        btn_regresar_menu: "ZURÜCK ZUM MENÜ 🚀",
        contact_title: "SOZIALE MEDIEN",
        contact_contracting: "Soziale Medien",
        btn_facebook: "FACEBOOK",
        btn_instagram: "INSTAGRAM",
        qr_heading: "QR-CODE SCANNEN",
        btn_share_qr: "QR TEILEN",
        cat2_t: "BILDERPORTFOLIO",
        cat2_c: "Größe auf dem Platz ist das Ergebnis unerschütterlicher Disziplin und ständigen Einsatzes. Mit voller Hingabe und absolutem Engagement in jedem Spiel hat er gezeigt, dass Erfolg Talent und Ausdauer verbindet und andere dazu inspiriert, ihre Träume mit dem Herzen zu verfolgen.",
        cat3_t: "GROSSE MOMENTE",
        cat3_c: "In den anspruchsvollsten Arenen des internationalen Fussballs zu konkurrieren bedeutet, den Stolz Mexikos und seiner Wurzeln auf höchstem Niveau zu präsentieren. Jedes Spiel ist das Ergebnis unerschütterlicher Disziplin und der Ehre, mit Leidenschaft, Einsatz und Authentizität auf dem Platz zu stehen.",
        lbl_mis_fortalezas: "Mexiko im Herzen",
        btn_tributo_tri: "Jonathans Tor",
        btn_junto_mar: "Interview mit Albacete",
        btn_con_gente: "Mexikos verstecktes Juwel",
        btn_ver_detalles: "DETAILS ANZEIGEN"
    },
    ja: {
        meta_title: "JONATHAN GÓMEZ",
        lbl_idioma: "言語",
        lbl_edition: "メキシコ系アメリカ人サッカー",
        lbl_hero_title: "JONATHAN GÓMEZ",
        btn_conoceme: "私について",
        btn_portafolio: "画像ポートフォリオ",
        btn_poder_musica: "偉大な瞬間",
        btn_contacto: "ソーシャルメディア",
        lbl_clic_reproducir: "クリックして再生",
        btn_grandes_momentos: "偉大な瞬間",
        modal_grandes_momentos_title: "偉大な瞬間",
        modal_grandes_momentos_desc: "画像をタップして拡大・スワイプしてください",
        btn_cerrar: "閉じる",
        btn_comparte_historia: "共有",
        lbl_producido_por: "プロデュース: \"TALENT CARD\"",
        btn_contactanos_card: "お問い合わせ",
        lbl_conoceme: "私について",
        lbl_biografia: "プロフィール",
        lbl_nombre_label: "氏名:",
        val_nombre: "Jonathan Germán Gómez Mendoza",
        lbl_edad_label: "ポジション:",
        val_edad: "左サイドバック / ディフェンダー",
        lbl_nacimiento_label: "出身:",
        val_nacimiento: "テキサス州フォートワース（メキシコ系）",
        lbl_nacionalidad_label: "国籍:",
        val_nacionalidad: "メキシコ系アメリカ人",
        lbl_estatura_label: "プロフィール / 経歴:",
        val_estatura: "国際エリートサッカー選手",
        lbl_formacion_titulo: "プロフェッショナル経歴",
        lbl_perfil_label: "プロフィール:",
        val_perfil_text: "ヨーロッパサッカー（レアル・ソシエダB）、メジャーリーグサッカー（MLS）でのプレー経験や、各国代表への選出歴を持つハイパフォーマンスプロアスリート。",
        lbl_desempeno_label: "パフォーマンス:",
        val_desempeno_text: "攻撃的なオーバーラップ、守備の堅実さ、高度な戦術理解力、そして毎試合で見せる絶対的な献身性で知られています。",
        lbl_especialidad_titulo: "専門分野",
        lbl_disciplina_label: "ディシプリン:",
        val_disciplina_text: "攻撃的志向、ダイナミックなトランジション、最高レベルの競争環境における戦術的厳格さを備えた左サイドバック。",
        lbl_tecnica_label: "テクニック:",
        val_tecnica_text: "左足の卓越した技術、正確なクロス、激しいマーク、そして国際舞台で培われた勝利へのメンタリティ。",
        lbl_logros_titulo: "主な実績とキャリア",
        val_logro_1: "📌 ヨーロッパや北米のハイレベルな競争環境で確実な足跡を残し、適応力と人間性を証明しながら国際サッカー界で定着。",
        val_logro_2: "⚽ プレッシャーのかかる大一番や国際大会の主役として、自らのルーツを誇りを持って体現し、ピッチ上で才能を証明。",
        val_logro_3: "🌐 揺るぎない規律、ピッチ内外での前向きなリーダーシップ、そしてたゆまぬ自己向上心を備えた、卓越したアスリートであり完全な人間性を持つ人物。",
        btn_regresar_menu: "メニューに戻る 🚀",
        contact_title: "ソーシャルメディア",
        contact_contracting: "ソーシャルメディア",
        btn_facebook: "FACEBOOK",
        btn_instagram: "INSTAGRAM",
        qr_heading: "QRコードをスキャン",
        btn_share_qr: "QR共有",
        cat2_t: "画像ポートフォリオ",
        cat2_c: "ピッチ上の偉大さは、揺るぎない規律と不断の努力の成果です。すべての試合における完全な献身と妥協のない姿勢により、成功には才能と粘り強さの両方が必要であることを示し、他の人々が心から夢を追い求めるようインスピレーションを与えています。",
        cat3_t: "偉大な瞬間",
        cat3_c: "国際サッカーの最も過酷な舞台で戦うことは、メキシコと自身のルーツの誇りを最高レベルで体現することを意味します。すべての試合は、揺るぎない規律と、情熱・献身・誠実さを持ってピッチで戦う名誉の結晶です。",
        lbl_mis_fortalezas: "心の中のメキシコ",
        btn_tributo_tri: "ジョナサンのゴール",
        btn_junto_mar: "アルバセテとのインタビュー",
        btn_con_gente: "メキシコに隠された至宝",
        btn_ver_detalles: "詳細を見る"
    },
    zh: {
        meta_title: "JONATHAN GÓMEZ",
        lbl_idioma: "语言",
        lbl_edition: "美墨混血足球运动员",
        lbl_hero_title: "JONATHAN GÓMEZ",
        btn_conoceme: "了解我",
        btn_portafolio: "图片作品集",
        btn_poder_musica: "精彩瞬间",
        btn_contacto: "社交媒体",
        lbl_clic_reproducir: "点击播放",
        btn_grandes_momentos: "精彩瞬间",
        modal_grandes_momentos_title: "精彩瞬间",
        modal_grandes_momentos_desc: "点击图片以放大并滑动查看",
        btn_cerrar: "关闭",
        btn_comparte_historia: "分享",
        lbl_producido_por: "由 \"TALENT CARD\" 制作",
        btn_contactanos_card: "联系我们",
        lbl_conoceme: "了解我",
        lbl_biografia: "生平简介",
        lbl_nombre_label: "姓名:",
        val_nombre: "Jonathan Germán Gómez Mendoza",
        lbl_edad_label: "场上位置:",
        val_edad: "左后卫 / 后卫",
        lbl_nacimiento_label: "出生地:",
        val_nacimiento: "得克萨斯州沃思堡（具有墨西哥血统）",
        lbl_nacionalidad_label: "国籍:",
        val_nacionalidad: "美墨双重国籍",
        lbl_estatura_label: "职业履历:",
        val_estatura: "国际精英足球运动员",
        lbl_formacion_titulo: "职业背景",
        lbl_perfil_label: "个人档案:",
        val_perfil_text: "高性能职业运动员，拥有欧洲足球（皇家社会B队）、美国职业足球大联盟（MLS）比赛经验以及多次国家队征召经历。",
        lbl_desempeno_label: "球场表现:",
        val_desempeno_text: "以其犀利的边路进攻、坚固的防守、先进的战术意识以及在每场比赛中的绝对投入而闻名。",
        lbl_especialidad_titulo: "专长领域",
        lbl_disciplina_label: "场上纪律:",
        val_disciplina_text: "具备进攻意识的左后卫，拥有动态转换能力以及在最高竞技压力下的战术严谨性。",
        lbl_tecnica_label: "技术特点:",
        val_tecnica_text: "左脚技术精湛，传中精准，逼抢凶狠，并具备在国际赛场上历练出的必胜信念。",
        lbl_logros_titulo: "成就与职业生涯",
        val_logro_1: "📌 在欧洲和北美的高水平竞争中稳步前进，展现出极强的适应能力与顽强品格，在国际足坛站稳脚跟。",
        val_logro_2: "⚽ 在高压对决和国际赛事中担任关键主角，自豪地代表自己的根源，并在球场上留下了才华的印记。",
        val_logro_3: "🌐 一名杰出的运动员和品格高尚的人，以其坚定不移的纪律性、场内外的积极领导力以及对自我超越的永恒追求而备受赞誉。",
        btn_regresar_menu: "返回菜单 🚀",
        contact_title: "社交媒体",
        contact_contracting: "社交媒体",
        btn_facebook: "FACEBOOK",
        btn_instagram: "INSTAGRAM",
        qr_heading: "扫描二维码",
        btn_share_qr: "分享二维码",
        cat2_t: "图片作品集",
        cat2_c: "球场上的伟大是坚如磐石的纪律和不懈努力的结果。通过在每场比赛中的全力以赴与绝对投入，他证明了成功是将才华与毅力完美结合，激励着他人用心去追逐梦想。",
        cat3_t: "精彩瞬间",
        cat3_c: "在国际足坛最高要求的舞台上竞争，意味着将墨西哥和家乡根基的骄傲提升到极致。每一场比赛都是坚定纪律的结晶，是在球场上用激情、奉献和真实自我去代表祖国的至高荣誉。",
        lbl_mis_fortalezas: "心系墨西哥",
        btn_tributo_tri: "乔纳森进球",
        btn_junto_mar: "阿尔巴塞特采访",
        btn_con_gente: "墨西哥的隐藏瑰宝",
        btn_ver_detalles: "查看详情"
    }
};

function changeLanguage(lang) {
    localStorage.setItem('selectedLanguage', lang);

    const elements = document.querySelectorAll('[data-i18n]');
    elements.forEach(el => {
        const key = el.getAttribute('data-i18n');
        if (translations[lang] && translations[lang][key]) {
            el.textContent = translations[lang][key];
        }
    });

    const altElements = document.querySelectorAll('[data-i18n-alt]');
    altElements.forEach(el => {
        const key = el.getAttribute('data-i18n-alt');
        if (translations[lang] && translations[lang][key]) {
            el.setAttribute('alt', translations[lang][key]);
        }
    });

    if (translations[lang] && translations[lang]['meta_title']) {
        document.title = translations[lang]['meta_title'];
    }

    document.querySelectorAll('.lang-chip').forEach(chip => {
        chip.classList.remove('active');
        if (chip.getAttribute('onclick').includes(`'${lang}'`)) {
            chip.classList.add('active');
        }
    });
}

document.addEventListener('DOMContentLoaded', () => {
    const savedLang = localStorage.getItem('selectedLanguage') || 'es';
    changeLanguage(savedLang);
});